#!/bin/bash

# Load Overrides File for overwriting Environment Variables in this file
# This will allow git pulls as they will overwrite this file, but not the overrides.env
# Format is VARIABLE=DATA
if ! [ -f ./overrides.env ]; then
	touch ./overrides.env
fi
. ./overrides.env

# Set Variables
# General
export COMPOSE_FLUENTD_SERVER="${FLUENTD_SERVER:-1.1.1.1}"
export COMPOSE_DOCKER_DATA="${DOCKER_DATA:-/opt/docker_data}"
export COMPOSE_DOCKER_CONFIG="${DOCKER_CONFIG:-/opt/docker_config}"

## Graylog Docker Compose Settings
export COMPOSE_GRAYLOG_PASSWORD_SECRET="${COMPOSE_GRAYLOG_PASSWORD_SECRET:-mysecret}"
export COMPOSE_GRAYLOG_ROOT_PASSWORD_SHA2="${COMPOSE_GRAYLOG_ROOT_PASSWORD_SHA2:-5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8}"
export COMPOSE_GRAYLOG_ROOT_EMAIL="${COMPOSE_GRAYLOG_ROOT_EMAIL}"
export COMPOSE_GRAYLOG_ES_CLUSTERNAME="${COMPOSE_GRAYLOG_ES_CLUSTERNAME:-graylog}"
export COMPOSE_GRAYLOG_ES_HOSTS="${COMPOSE_GRAYLOG_ES_HOSTS:-elasticsearch:9300}" # EX: es-node-1.example.org:9300,es-node-2.example.org:9300
export COMPOSE_GRAYLOG_MAILHOST="${COMPOSE_GRAYLOG_MAILHOST:-mailhost.mail.com}"
export COMPOSE_GRAYLOG_MAILPORT="${COMPOSE_GRAYLOG_MAILPORT:-25}"
export COMPOSE_GRAYLOG_MAILAUTHUSERNAME="${COMPOSE_GRAYLOG_MAILAUTHUSERNAME:-username}"
export COMPOSE_GRAYLOG_MAILAUTHPASSWORD="${COMPOSE_GRAYLOG_MAILAUTHPASSWORD:-password}"
export COMPOSE_GRAYLOG_URL="${COMPOSE_GRAYLOG_URL}"
export COMPOSE_MONGODB_SERVER="${COMPOSE_MONGODB_SERVER:-mongodb}"
export COMPOSE_GRAYLOG_DS_MULTICAST_ENABLED="${COMPOSE_GRAYLOG_DS_MULTICAST_ENABLED:-false}"
export COMPOSE_GRAYLOG_ES_NODE_MASTER="${COMPOSE_GRAYLOG_ES_NODE_MASTER:-false}"
export COMPOSE_GRAYLOG_ES_NODE_DATA="${COMPOSE_GRAYLOG_ES_NODE_DATA:-false}"
export COMPOSE_GRAYLOG_WEB_ENDPOINT_URI='${COMPOSE_GRAYLOG_WEB_ENDPOINT_URI}:-http://1.1.1.1:9000/api'
export COMPOSE_GRAYLOG_TRANSPORT_EMAIL_FROM_EMAIL='${COMPOSE_GRAYLOG_TRANSPORT_EMAIL_FROM_EMAIL:-mail@test.com}'

docker-compose "$@"










